# Generated by Django 5.1.2 on 2024-10-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('gear', models.CharField(max_length=50)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=50)),
                ('state_number', models.CharField(max_length=50)),
                ('engine', models.BooleanField(default=False)),
                ('open_doors', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model')),
            ],
        ),
    ]
